### PR TITLE
James matchett ICMP Flood Method Addition 

### PR DESCRIPTION
**Pull request by JamesMatchett**
As per Issue #64 requesting more attack methods

Adds the ability for ICMP flood style attacks both with and without data being added to the ping by toggling the append random chars flag where if chosen appends between 0 and 65500 random bytes to the ping buffer. Also using the Sockets/thread as a selector for pings sent per thread.

I've kept the coding for this method as similar to that for other methods within the LOIC. 

Things I want to change: update all GUI options so that irrelevant ones are non-selectable, i did this with most but not all options on screen. 

Added the method to ChLDos.cs and made appropriate additions to protocol.cs and frmMain.cs to make it all work, I feel it's a good addition for testing and I believe I could improve how the method works over time.

### CODE REVIEW

**Comment by JamesMatchett** [comment]
Apologies for the massive amounts of "files changed" it appears on one of the commits I may have uploaded the entire folder without making any alterations

**Comment by NewEraCracker** [comment]
What editor are you using to edit the files? What client are you using to upload them?

**Comment by JamesMatchett** [comment]
using visual studio to develop, i made an error when uploading, would you like me to make a new fork from master and upload the updated files? and I'm using chrome browser to commit files.

**Comment by NewEraCracker** [comment]
I appreciate your effort but please use the windows git client instead of a browser. It will probably prevent this gigantic mess.

Thanks.

**Comment by JamesMatchett** [comment]
no worries I get started on that right away! sorry for the mess still finding my way around github, Thanks a bunch for the prompt reply , Should i close this and make a new pull request when ready?

**Comment by NewEraCracker** [comment]
I'll close this. Submit another one when ready. Thanks.

**Pull request closed without merging**
