### PR TITLE
James Matchett- Add ICMP attack method 

### PR DESCRIPTION
**Pull request by JamesMatchett**
Hopefully Commit coming through clearer now, 

As per issue #64 

Adds the option for ICMP (ping flood) attacks either with no data in the buffer sent with the ping or a random amount of random bits (up to 65500) in the buffer.

Random bits selected with the "Append random chars" checkbox when ICMP is selected in the method box and number of pings per thread selected with Sockets/thread when ICMP is selected.

Things I would change: Drop port number from ICMP method call in cHLDos.cs as it is unnecessary in ICMP pings. I would also like to go over the GUI checkboxes selectable when ICMP is selected.

Thanks a bunch, James

### CODE REVIEW

**Comment by NewEraCracker** [comment]
Looks good. Thanks a lot. I may do some changes before integrating on master.

**Comment by JamesMatchett** [comment]
That's brilliant, thank you very much :)- James

**Comment by NewEraCracker** [comment]
Have you pushed the latest commit through browser or git client? It introduced a gigantic amount of whitespace changes.

**Comment by JamesMatchett** [comment]
Apologies, bad commit on my part a few mintues ago, will revert.

**Comment by JamesMatchett** [comment]
Hi, sorry again for the stupid mistake, I've pushed the files from git desktop from home. I tried pushing the master then pushing my changes after that so changes only would be highlighted. The large diff number is still appearing. Do you think a new pull request would be the easiest option or is there a better way?

Sorry again, James

**Comment by NewEraCracker** [comment]
Yeah, just do another pull request. Sorry for the hassle.

**Comment by JamesMatchett** [comment]
not a problem, I've learnt my lesson, stick to git dekstop from now on. Will have that done soon :)

**Pull request closed without merging**
